package Utils;

public enum ButtonType {
    UPGRADEMEAT , UPGRADEHONEY ,UPGRADEDNA, NAVIGATORPLAYER , NAVIGATORENEMY , NAVIGATORGOBLET , NAVIGATORDNA , BACK , UPGRADECHICKEN , UPGRADECOW , UPGRADESHEEP
}
